export const GET_PROFILE_FLAG="GET_PROFILE_FLAG";
export const SET_PROFILE_FLAG="SET_PROFILE_FLAG";
export const UPDATE_PROFILE= "UPDATE_PROFILE";
export const PROFILE_RESET= "PROFILE_RESET";
export const UPDATE_BUY_STATE= "UPDATE_BUY_STATE";
export const FETCH_IMAGES="FETCH_IMAGES";
export const IMAGE_LIST_LENGTH="IMAGE_LIST_LENGTH";